export const UI_LABELS = {
  freeLessons: "🎓 3 lecții gratuite",
  marathon: "🚀 Maraton de engleză",
  fearSpeaking: "🗣️ Cum scapi de frica de a vorbi",
  teachingMethod: "🎥 Metoda noastră",
  website: "🌐 Website",
  operator: "💬 Discută cu echipa noastră",
  careerAstrology: "🔮 Consultație astrologică în carieră",
  askAi: "🤖 Întreabă AI-ul",
  backToMenu: "⬅️ Meniul principal",
  acceptPrivacy: "✔ Accept",
  yes: "Da",
  no: "Nu",
  sendPhone: "📱 Trimite numărul",
  writePhoneManually: "Voi scrie manual",
  wantsCourse: "📞 Vreau la curs",
  wantsCourseInfo: "📞 Vreau să aflu despre curs",
  openLesson: "▶️ Deschide lecția",
  openLessonInBrowser: "🌐 Deschide separat",
  streamLesson: "🎬 Începe lecția",
  testYourself: "📝 Test după lecție",
  viewServices: "🌐 Deschide website-ul",
  contactForPackage: "📩 Contactează pentru acest pachet",
  wantsAstrologyConsultation: "🔮 Vreau o consultație",
  opsHelp: "ℹ️ Ajutor",
} as const;

export const SHARED_COPY = {
  chooseHowToContinue: "Alege cum vrei să continuăm:",
  continueFromWhereLeftOff: "Continuăm exact de unde ai rămas.",
  phoneFormatPrompt: "Te rog să scrii numărul tău în formatul +373XXXXXXXX.",
  invalidPhonePrompt:
    "Numărul nu pare valid. Te rog să încerci formatul +373XXXXXXXX sau să folosești butonul dedicat.",
  onboardingMenuPrompt: "Alege din meniu opțiunea dorită și începem.",
  useMainMenuPrompt: "Folosește meniul principal pentru a continua.",
  startMenuActivationRequired: "Mai întâi activează accesul din meniul de start.",
  commercialContactRequired: "Înainte de flow-ul comercial, am nevoie de datele de contact de bază.",
  acceptPrivacyRequired: "Pentru a continua, apasă butonul ✔ Accept.",
} as const;
